let rp="         Report Card";
let name="Name: Sulagna Banerjee";
let school="School: AAS";
let section="Section: C";
let grade="Grade: A+";
let rollno= "Roll No: 22";
console.log(rp);
console.log();
console.log(name);
console.log();
console.log(school);
console.log();
console.log(section);
console.log();
console.log(grade);
console.log();
console.log(rollno);
console.log();
sub1="Maths: 98/100";
console.log(sub1);
console.log();
sub2="English: 87/100";
console.log();
console.log(sub2);
console.log();
sub3="Science: 99/100";
console.log(sub3);